### ISSUE TITLE
How does one edit this project?

### ISSUE THREAD

**Issue by psinghsp** [mapbox/osm-bright#104]
I did a get on the entire project and tried to open the project in TileMill. But it seems like TileMill no longer recognizes the contents.

What do developers of this project use to edit all the styles?

**Comment by tmcw** [comment]
We use(d) TileMill (we no longer use this project at Mapbox). TileMill should recognize the contents.

**Comment by psinghsp** [comment]
There is a big difference in "should recognize" and "does recognize". It DOES NOT recognize. Does that mean its a bug? Should someone fix the project so that it does open properly in TileMill?
