### ISSUE TITLE
Japanese, Chinese, Korean not properly displayed 

### ISSUE THREAD

**Issue by tsanders42** [mapbox/osm-bright#120]
Just like with issue #103: Japanese (and Korean and Chinese) characters aren't properly displayed:
![image](https://cloud.githubusercontent.com/assets/1888751/18253464/2323ede4-7395-11e6-8eaf-6eb1b0bcc5a8.png)

OSMBright.xml has both 'Unifont Medium' and 'unifont Medium':
![image](https://cloud.githubusercontent.com/assets/1888751/18253473/2ee872bc-7395-11e6-9206-fa25f77d260f.png)
(as does palette.mss)

any thoughts on how I can fix this?

Thank you for your help

**Comment by tmcw** [comment]
Do you have Unifont installed? Do you see any font warnings in the rendering process?

**Comment by tsanders42** [comment]
Found it:
the guide at https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/ instructed me to set the font directory as:

`font_dir=/usr/share/fonts/truetype/ttf-dejavu`

after changing it to:

`font_dir=/usr/share/fonts/truetype`

non-latin fonts are properly displayed.

thank you for nudging me in the right direction :)
