### ISSUE TITLE
Different themes

### ISSUE THREAD

**Issue by jacobtoye** [mapbox/osm-bright#60]
Hi guys,

I really love your work! The open source effort of MapBox is amazing :)

I was wondering if you had any plans, or even wanted, to expand osm-bright to support different themes? I've forked osm-bright and changed the sytlesheets to provide a different theme. See: https://github.com/jacobtoye/osm-bright

I'd love to hear your thoughts.

**Comment by tmcw** [comment]
Closing; feel free to use the @jacobtoye fork for themes.
