### ISSUE TITLE
Tilemill as mapbox, Compound line styles

### ISSUE THREAD

**Issue by Pancake08** [mapbox/osm-bright#77]
hey guys,

i have a problem. while creating a map with tilemill, a problem appears.
At first, here a little explanation what i want to create :)
I want to create/desgin the streets like on 
https://www.mapbox.com/tilemill/docs/guides/styling-lines/
See "Compound line styles".
To create this i had to group the roads in classes, so i thought is take the same column "type". And now here is my problem, after adding the code to my project, tilemill hasnt rendered none of these streests. So i hang in and tyied to understand how this grouping works. So i have seen( like in the link below) that the types are called sub_types. but why it still dont work? spme ideas maybe?

```
#highway {
  text-name: '[name]';
  text-face-name: 'Helvetica Neue Regular';
  text-placement: line;
  text-size: 18;
  line-width:2;
//  line-color:#FFd400;
  
  [sub_type='motorway_junction'] {
    ::case {     
      line-width: 5;
      line-color:#FF4000;
    }
    ::fill {
      line-width: 2.5;
      line-color:#ffd400;
    }
  }
  [sub_type='secondary'] {
    ::case {
      line-width: 4.5;
      line-color:#A4A4A4;
    }
    ::fill {
      line-width: 2;
      line-color:#f5fdf0;
    }
  }
}
```

And here is a screenshot of the database of highway.

**Comment by tmcw** [comment]
Closing; no response.
