### ISSUE TITLE
Incorrect attribution parameter - OSM Data is now ODBL

### ISSUE THREAD

**Issue by rnorris** [mapbox/osm-bright#96]
Currently in both mml files they have this statement.
  "attribution": "Data \u00a9 OpenStreetMap (and) contributors, CC-BY-SA", 

OSM Data is ODBL since April 2012 and not CC-BY-SA.

**Comment by tmcw** [comment]
Fixed in 4cd7e8e1752bacac2ee2047dd0363648990ecb01
